apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: apps
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: aoms/mock_frontend_python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: API_URL
              value: http://backend.apps.svc.cluster.local:80/
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer