apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apps
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aoms/mock_backend_python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      restartPolicy: Always
  selector:
    matchLabels:
      app: backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP